server:
  port: 9527
spring:
  application:
    name: springcloud-zuul-gateway
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
  instance:
      instance-id: springcloud-zuul-gateway
      prefer-ip-address: true
info:
  app.name: linxiaomi-springcloud
  company.name: https://github.com/linxiaomi
  build.artifactId: springcloud-zuul-gateway
  build.version: 1.0-SNAPSHOT
zuul:
#  prefix: /linxiaomi
#  ignored-services: "*"
  routes:
    mydept.serviceId: springcloud-dept
    mydept.path: /mydept/**